import argparse
import os
import sys
from pathlib import Path

import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, REPO_ROOT)
sys.path.insert(0, SCRIPT_DIR)

from general_motion_retargeting import RobotMotionViewer
from pkl_to_csv import ROBOT_LAYOUTS, validate_robot_joint_layout


def extend_roban_s14_dof(dof_pos: np.ndarray) -> np.ndarray:
    extend_dof_pos = np.zeros((dof_pos.shape[0], dof_pos.shape[1] + 2), dtype=dof_pos.dtype)
    extend_dof_pos[:, :13] = dof_pos[:, :13]
    extend_dof_pos[:, 13:17] = dof_pos[:, 13:17]
    extend_dof_pos[:, 18:22] = dof_pos[:, 17:21]
    return extend_dof_pos


def load_csv_motion(csv_path: Path, robot_type: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    layout = ROBOT_LAYOUTS[robot_type]
    validate_robot_joint_layout(layout)

    motion = np.loadtxt(csv_path, delimiter=",", dtype=np.float64)
    if motion.ndim == 1:
        motion = motion.reshape(1, -1)

    expected_cols = 3 + 4 + layout.expected_total_dof
    if motion.shape[1] != expected_cols:
        raise ValueError(
            f"CSV has {motion.shape[1]} columns, expected {expected_cols} for {robot_type} "
            f"(root_pos 3 + root_rot 4 + dof_pos {layout.expected_total_dof})."
        )

    root_pos = motion[:, :3]
    root_rot = motion[:, 3:7][:, [3, 0, 1, 2]]
    csv_dof_pos = motion[:, 7:]

    dof_pos = np.zeros_like(csv_dof_pos)
    dof_pos[:, list(layout.ordered_indices)] = csv_dof_pos

    if robot_type == "roban_s14":
        dof_pos = extend_roban_s14_dof(dof_pos)

    return root_pos, root_rot, dof_pos


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize a robot motion CSV file.")
    parser.add_argument(
        "--robot",
        type=str,
        default="roban_s14",
        choices=sorted(ROBOT_LAYOUTS.keys()),
    )
    parser.add_argument(
        "--csv_path",
        "--robot_motion_path",
        dest="csv_path",
        type=Path,
        required=True,
        help="Path to a CSV file generated by scripts/pkl_to_csv.py.",
    )
    parser.add_argument(
        "--motion_fps",
        type=int,
        default=50,
        help="Playback FPS. CSV files do not store fps, so this defaults to 50.",
    )
    parser.add_argument("--record_video", action="store_true")
    parser.add_argument("--video_path", type=str, default="videos/example.mp4")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    if not args.csv_path.is_file():
        raise FileNotFoundError(f"Motion CSV file {args.csv_path} not found")

    motion_root_pos, motion_root_rot, motion_dof_pos = load_csv_motion(args.csv_path, args.robot)

    env = RobotMotionViewer(
        robot_type=args.robot,
        motion_fps=args.motion_fps,
        camera_follow=False,
        record_video=args.record_video,
        video_path=args.video_path,
    )

    frame_idx = 0
    try:
        while True:
            env.step(
                motion_root_pos[frame_idx],
                motion_root_rot[frame_idx],
                motion_dof_pos[frame_idx],
                rate_limit=True,
            )
            frame_idx += 1
            if frame_idx >= len(motion_root_pos):
                frame_idx = 0
    except KeyboardInterrupt:
        pass
    finally:
        env.close()
